
#회원정보 데이블
CREATE TABLE REST_MEMBER (
	MEM_ID VARCHAR(10) PRIMARY KEY
	, MEM_NAME VARCHAR(10) NOT NULL
	, MEM_AGE INT DEFAULT 0
	, MEM_TEL VARCHAR(15) UNIQUE
);

SELECT * FROM REST_MEMBER;

INSERT INTO REST_MEMBER VALUES ('aaa', 'kim', 20, '010-6666-1111');
INSERT INTO REST_MEMBER VALUES ('bbb', 'hong', 30, '010-4444-2222');
INSERT INTO REST_MEMBER VALUES ('ccc', 'choi', 25, '010-5555-3333');

COMMIT;

#회원 한 명의 모든 컬럼 정보를 조회
SELECT *
FROM rest_member
WHERE MEM_ID = 'aaa';


SELECT *
FROM rest_member
WHERE MEM_ID = 'aaa';
AND MEM_AGE = 20;

#회원정보 등록
INSERT INTO rest_member (MEM_ID, MEM_NAME, MEM_AGE, MEM_TEL) 
VALUES ('ddd', 'park', 50, '010-3923-8721');

#게시글 정보 테이블
CREATE TABLE REST_BOARD (
	BOARD_NUM INT PRIMARY KEY
	, TITLE VARCHAR(10) NOT NULL
	, CONTENT VARCHAR(20)
	, WRITER VARCHAR(10)
);

INSERT INTO REST_BOARD VALUES (1, '제목1', '내용1', 'KIM');
INSERT INTO REST_BOARD VALUES (2, '제목2', '내용2', 'KIM');
INSERT INTO REST_BOARD VALUES (3, '제목3', '내용3', 'KIM');
COMMIT;

SELECT * FROM REST_BOARD;

UPDATE rest_member 
SET
MEM_NAME = 'HONG',
MEM_AGE = 56
WHERE MEM_ID = 'aaa';


#상픔정보 테이블
CREATE TABLE REST_ITEM (
	ITEM_CODE INT PRIMARY KEY AUTO_INCREMENT
	, ITEM_NAME VARCHAR(20) NOT NULL
	, ITEM_PRICE INT
	, ITEM_COLOR VARCHAR(10)
);

SELECT * FROM REST_ITEM;

INSERT INTO REST_ITEM (ITEM_NAME, ITEM_PRICE, ITEM_COLOR) 
VALUES ('청바지', 30000, '파란색');

ROLLBACK;







